### ISSUE TITLE
Create new blocks API

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha.io#18]
Add API endpoint to download all operations not yet in Stellar/IPFS blockchain and create a new block

**Comment by ataki** [comment]
@markulrich is this still up for grabs? I remember chatting about this, would be interested to take a look if you haven't already done something

**Comment by markulrich** [comment]
Yea go for it!

**Comment by markulrich** [comment]
Moved to https://github.com/rahafoundation/blockchain repo
