### ISSUE TITLE
Add backup/restore scripts for firestore db

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha.io#25]
@ataki have you already done some work here?

**Comment by ataki** [comment]
backup tool is at https://github.com/ataki/raha.backup .I decided to make it a separate repo since this repo should be the web app, lmk if you want to bring that utility in here or into the rahafoundations org.

**Comment by markulrich** [comment]
Separate repo in rahafoundations sounds good! Maybe named firebase-backup?

**Comment by ataki** [comment]
done! closing this out
