### ISSUE TITLE
Create "invite new user" page

### ISSUE THREAD

**Issue by markulrich** [rahafoundation/raha.io#8]
Create a page explaining how to make invite video for new members

**Comment by ataki** [comment]
question around this issue - what does the invite process look like, and what pieces of information do we need from the user? is just a list of emails good enough for now?

**Comment by markulrich** [comment]
We should think about what sign up process will look like when people are making a video in-person. Main hurdle will be creation of that video, so after that we want to make everything else as easy as possible. Maybe something like:

1. A Raha member tells someone they trust about Raha, shows them the FAQ page and explains how it could improve security and equality
1. On the friend's phone, they make the video and the friend uploads it to Youtube (supporting Facebook video URLs would also be great)
1. The friend goes to raha.io/me and signs in with Google/Facebook, then is brought to raha.io/signup and enters (to a prepopulated form) their full name, video link, and user name of person who invited them.
1. The original member goes to the new member's page and trusts them to indicate "yes I invited this person." It's this last part that's a bit hacky, but hopefully original member is highly motivated (so it's the new member we want to give ideal experience to).

This would a) encourage people to do everything in person and b) make it so we aren't managing any user emails or risking spamming people who are inviting everyone they know.

Is this already too complex? Can we think of a more simple MVP?

At a later point, we should think through how remote invites work.

This is of course a very rough first sketch. Getting this right will be essential.
